---
title: "Rate This Interruption"
output:
  html_document:
    df_print: paged
---


```{r, echo = FALSE, message = FALSE}
#Load Materials
library(googlesheets4)
library(tidyverse)
library(ThemePark)
library(scales)
library(janitor)

couples <- read_sheet(ss = "https://docs.google.com/spreadsheets/d/1R8WJhW0E-5_SnKRsT66lw4UuY45dezcGFVhQgJG2LIA/edit?usp=sharing", 
                      sheet = "Unique_Couples")
couples <- clean_names(couples)
couples <- couples |> 
  filter(!exclude) |> 
  mutate(show = unlist(show)) |> 
  dplyr::select(-starts_with(c("make_it_official", "exclude")), -already_together, -imdb_id)
```

```{r}
couples |>
  ggplot(aes(x = mentions)) +
  geom_bar(fill = "purple") +
  theme_barbie() +
  labs(title = "Who are we talking about?",
       x = "Number of Mentions",
       y = "Number of Couples")
```

Who are our power couples? These guys are in the tail of the distribution.

```{r}
couples |> 
  filter(mentions > 10) |> 
  dplyr::select(show, couple, mentions)
```

```{r}
couples |>
  group_by(show) |>
  summarize(year = mean(year_of_start)) |>
  ggplot(aes(x = year)) +
  geom_bar(fill = "purple") +
  theme_barbie() +
  labs(title = "When are we debuting?",
       x = "Year of Start",
       y = "Number of Shows")
```

Who are our top 3 oldies and top three new shows?

```{r}
rbind(couples |> 
        group_by(show) |>
        summarize(year = first(year_of_start)) |>
        arrange(year) |> 
        head(3),
      couples |> 
        group_by(show) |>
        summarize(year = first(year_of_start)) |>
        arrange(year) |>
        tail(3))

```

```{r}
couples |>
  group_by(show) |>
  summarize(year = as.character(first(year_of_start))) |>
  mutate(decade = case_when(
    grepl("197", year) ~ "1970s",
    grepl("198", year) ~ "1980s",
    grepl("199", year) ~ "1990s",
    grepl("200", year) ~ "2000s",
    grepl("201", year) ~ "2010s",
    grepl("202", year) ~ "2020s"
  )) |>
  ggplot(aes(x = decade)) +
  geom_bar(fill = "purple") +
  theme_barbie() +
  labs(title = "What decades do we have?",
       x = "",
       y = "Number of Shows")
```

```{r}
couples |>
  group_by(show) |>
  summarize(pairs = n()) |>
  ggplot(aes(x = pairs)) +
  geom_bar(fill = "purple") +
  theme_barbie() +
  labs(title = "How many couples do we have per show?",
       x = "Number of Couples",
       y = "Number of Shows")
```

Who are our super romantic shows?
```{r}
couples |>
  group_by(show) |>
  summarize(pairs = n()) |>
  filter(pairs > 2)
```

```{r}
couples |>
  #compute percentage of show to go as difference in seasons over total
  mutate(perc_seasons_to_go = (num_seasons - first_kiss_season)/num_seasons) |>
  ggplot(aes(x = perc_seasons_to_go)) +
  #bin at 10%
  geom_histogram(binwidth = 0.10, fill = "purple") +
  scale_x_continuous(labels = scales::percent) +
  coord_flip() +
  labs(x = "Percentage of Show to Go", y = "Number of Couples",
       title = "How early are these kisses happening?",
       subtitle = "Early. Much earlier than I thought.") +
  theme_barbie()
```

Who's a last season kisser?
```{r}
couples |>
  filter(num_seasons == first_kiss_season)
```

```{r}
couples |>
  #compute percentage of show to go as difference in seasons over total
  mutate(perc_seasons_to_go = (num_seasons - first_kiss_season)/num_seasons) |>
  mutate(decade = case_when(
    grepl("197", year_of_start) ~ "1970s",
    grepl("198", year_of_start) ~ "1980s",
    grepl("199", year_of_start) ~ "1990s",
    grepl("200", year_of_start) ~ "2000s",
    grepl("201", year_of_start) ~ "2010s",
    grepl("202", year_of_start) ~ "2020s"
  )) |>
  ggplot(aes(x = perc_seasons_to_go, group = decade)) +
  #bin at 10%
  geom_histogram(binwidth = 0.10, fill = "purple") +
  scale_x_continuous(labels = scales::percent) +
  coord_flip() +
  facet_wrap(vars(decade)) +
  labs(x = "Percentage of Show to Go", y = "Number of Couples",
       title = "How early are these kisses happening?",
       subtitle = "(and does it vary by decade)",
       caption = "(still much earlier than I thought)") +
  theme_barbie()
```

Now, to read in the ratings data.
```{r}
ratings <- read_sheet(ss = "https://docs.google.com/spreadsheets/d/1R8WJhW0E-5_SnKRsT66lw4UuY45dezcGFVhQgJG2LIA/edit?usp=sharing", 
                      sheet = "Episode_Ratings")
ratings <- clean_names(ratings)

# Exclude ratings rows with missing data
ratings <- ratings[complete.cases(ratings), ]
```

Now, to join the two.

```{r, warning = FALSE}
# Left-join episodes and ratings into the couples
ratings_couples <- couples[1:20, ] |> 
  left_join(ratings, 
            by = join_by(show == show))
            

# Create an indicator variable for episodes that aired after first kiss
ratings_couples <- ratings_couples |> 
  group_by(show, couple) |> 
  mutate(show_couple_id = 1:n(), 
         is_first_kiss_ep = season == first_kiss_season & episode == first_kiss_episode,
         first_kiss_id = min(ifelse(test = is_first_kiss_ep, yes = show_couple_id, no = 9999)),
         after_first_kiss = show_couple_id > first_kiss_id) |> 
  dplyr::select(-is_first_kiss_ep) |>
  mutate(eps_since_kiss = show_couple_id - first_kiss_id) |>
  ungroup()
```

```{r}
#center on first kiss before fitting the model
its_mod <- lm(data = ratings_couples,
              rating ~ eps_since_kiss + after_first_kiss + eps_since_kiss * after_first_kiss)
ratings_couples |>
  dplyr::mutate(fit = its_mod$fitted.values) |>
  ggplot(aes( x = eps_since_kiss, y = rating, group = after_first_kiss)) +
  geom_point(aes(color = after_first_kiss), alpha = 0.5) +
  geom_line(aes(y = fit))
```

```{r}
ratings_couples |> 
  dplyr::mutate(fit = its_mod$fitted.values) |>
  filter(show == "New Girl") |>
  ggplot(aes(x = eps_since_kiss, y = rating, group = after_first_kiss)) +
  geom_point(aes(color = after_first_kiss), alpha = 0.5) +
  geom_line(aes(y = fit)) +
  theme_barbie() +
  labs(title = "I meant something like that",
       subtitle = "jess and nick <3") +
  theme(plot.title = element_text(size = 10),
        plot.subtitle = element_text(size = 8),
        axis.title = element_text(size = 8),
        axis.text = element_text(size = 8),
        legend.title = element_text(size = 8)) +
  scale_color_manual(values = c("TRUE" = "blue", "FALSE" = "darkgray"))
  
```